name: Build WebSharper 5 Stack

on:
  workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    permissions:
      packages: write
      contents: read
      
    env: 
      WSPackageFolder: ../localnuget
      BUILD_NUMBER: ${{ github.run_number }}
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} 
    
    steps:
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/dotnet-websharper/index.json

    - name: Check out WS Core
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/core
        ref: websharper50
        path: core

    - name: Build WS Core
      run: ./build CI-Release
      working-directory: ./core

    - name: Check out WS.UI
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/ui
        ref: websharper50
        path: ui
        
    - name: Build WS.UI
      run: ./build CI-Release
      working-directory: ./ui

    - name: List packages within ./localnuget
      run: ls ./localnuget

    - name: Publish Nuget packages to GitHub registry
      run: dotnet nuget push *.nupkg -k $NUGET_AUTH_TOKEN
      working-directory: ./localnuget
