name: 4. Publish to WebSharper CDN

on:
  workflow_dispatch

jobs:
  publishcdn:

    runs-on: windows-latest
          
    env: 
      CDN_WEBSHARPER_COM_LOGIN: ${{ secrets.CDN_WEBSHARPER_COM_LOGIN }}

    steps:
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Check out build-script
      uses: actions/checkout@v2

    - name: Run CDN Publisher
      run: dotnet fsi Publisher.fsx
