name: 3. Publish WebSharper Core Stack

on:
  workflow_dispatch:
    inputs:
      buildRunNumber:
        description: 'Select build run number'
        required: false
        default: ''
      exclude:
        description: 'Package name patterns to exclude from publishing, separate by semicolon'
        required: false
        default: ''

jobs:
  publish:

    runs-on: windows-latest
      
    steps:

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Download Packages Artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: build-stack.yml
        run_number: ${{ github.event.inputs.buildRunNumber }}
        name: Packages
        path: Packages

    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          package-exclude.fsx
        sparse-checkout-cone-mode: false

    - name: Exclude packages
      run: dotnet fsi ./package-exclude.fsx '${{ github.event.inputs.exclude }}'
      shell: bash

    - name: Push to NuGet
      run:
        dotnet nuget push *.nupkg
          --api-key ${{ secrets.NUGET_API_KEY }}
          --source https://api.nuget.org/v3/index.json
          --skip-duplicate
          --timeout 1800
      working-directory: ./Packages
