name: 2. Test WebSharper Templates

on:
  workflow_dispatch:
    inputs:
      nugetversion:
        description: 'Specify NuGet version'
        required: false
        default: ''
      dotnetVersion:
        description: 'Select .NET SDK version'
        required: false
        default: '6.0.x'

jobs:
  test:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
          
    steps:
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ github.event.inputs.dotnetVersion }}
        
    - name: Add GitHub registry NuGet source
      run: 
        dotnet nuget 
          add source https://nuget.pkg.github.com/dotnet-websharper/index.json 
          --name github 
          --username intellifactory-gh 
          --password ${{ secrets.PAT_PACKAGE }} 
          --store-password-in-clear-text

    - name: Check out build-script
      uses: actions/checkout@v2

    - name: Create and build WS Templates
      run: |
        chmod +x ./test-templates.sh
        ./test-templates.sh "${{ github.event.inputs.dotnetVersion }}" "${{ github.event.inputs.nugetversion }}"
      shell: bash
