name: Update WebSharper Core Stack

on:
  workflow_dispatch:
    inputs:
      updateFolder:
        description: "Select which folder's update.cmd to run"
        required: true

env:
    GITHUB_TOKEN: ${{ secrets.PAT_PR }}
    PR_TOKEN: ${{ secrets.PAT_PR }}

permissions:
  pull-requests: write

jobs:
  update:

    runs-on: windows-latest

    steps:
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Add GitHub registry NuGet source
      run: 
        dotnet nuget 
          add source https://nuget.pkg.github.com/dotnet-websharper/index.json 
          --name github 
          --username intellifactory-gh 
          --password ${{ secrets.PAT_PACKAGE }} 
          --store-password-in-clear-text

    - name: Install Paket as global tool
      run: dotnet tool install paket --global

    - name: Add credentials for Paket
      run:
        paket config
          add-credentials https://nuget.pkg.github.com/dotnet-websharper/index.json
          --username intellifactory-gh 
          --password ${{ secrets.PAT_PACKAGE }}
          
    - name: Configure IntelliFactory CI git user
      run: |
        git config --global user.email "ci@intellifactory.com"
        git config --global user.name "IntelliFactory CI"

    - name: Check out build-script
      uses: actions/checkout@v2
      with:
        path: build-script

    - name: Check out WS Core
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/core
        ref: master
        path: core
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS Core
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./core

    - name: Check out WS.UI
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/ui
        ref: master
        path: ui
        token: ${{ secrets.PAT_PACKAGE }}
        
    - name: Update WS.UI
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./ui

    - name: Check out WS.AspNetCore.WebSocket
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/aspnetcore
        ref: master
        path: aspnetcore
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}
        
    - name: Update WS.AspNetCore.WebSocket
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./aspnetcore

    - name: Check out WS.Templates
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/templates
        ref: master
        path: templates
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}
        
    - name: Update WS.Templates
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./templates

    - name: Check out WS.JQuery
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/jquery
        ref: master
        path: jquery
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.JQuery
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./jquery

    - name: Check out WS.Forms
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/forms
        ref: master
        path: forms
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Forms
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./forms
      
    - name: Check out WS.MVU
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/mvu
        ref: master
        path: mvu
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}
    
    - name: Update WS.MVU
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./mvu

    - name: Check out WS.Leaflet
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/leaflet
        ref: master
        path: leaflet
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Leaflet
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./leaflet

    - name: Check out WS.D3
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/d3
        ref: master
        path: d3
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.D3
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./d3

    - name: Check out WS.React
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/react
        ref: master
        path: react
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.React
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./react

    - name: Check out WS.SignalR
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/signalr
        ref: master
        path: signalr
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.SignalR
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./signalr

    - name: Check out WS.DateFNS
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/datefns
        ref: master
        path: datefns
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.DateFNS
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./datefns

    - name: Check out WS.Moment
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/moment
        ref: master
        path: moment
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Moment
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./moment

    - name: Check out WS.Plotly
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/plotly
        ref: master
        path: plotly
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Plotly
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./plotly

    - name: Check out WS.ChartJS
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/chartjs
        ref: master
        path: chartjs
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Chartjs
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./chartjs

    - name: Check out WS.Charting
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/charting
        ref: master
        path: charting
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Charting
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./charting

    - name: Check out WS.Highcharts
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/highcharts
        ref: master
        path: highcharts
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Highcharts
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./highcharts
      
    - name: Check out WS.HighlightJS
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/highlightjs
        ref: master
        path: highlightjs
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.HighlightJS
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./highlightjs

    - name: Check out WS.MathJax
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/mathjax
        ref: master
        path: mathjax
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.MathJax
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./mathjax

    
