name: Update WebSharper Core Stack

on:
  workflow_dispatch:
    inputs:
      updateFolder:
        description: "Select which folder's update.cmd to run"
        required: true

env:
    GITHUB_TOKEN: ${{ secrets.PAT_PR }}
    PR_TOKEN: ${{ secrets.PAT_PR }}

permissions:
  pull-requests: write

jobs:
  update:

    runs-on: windows-latest

    steps:
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Add GitHub registry NuGet source
      run: 
        dotnet nuget 
          add source https://nuget.pkg.github.com/dotnet-websharper/index.json 
          --name github 
          --username intellifactory-gh 
          --password ${{ secrets.PAT_PACKAGE }} 
          --store-password-in-clear-text

    - name: Install Paket as global tool
      run: dotnet tool install paket --global

    - name: Add credentials for Paket
      run:
        paket config
          add-credentials https://nuget.pkg.github.com/dotnet-websharper/index.json
          --username intellifactory-gh 
          --password ${{ secrets.PAT_PACKAGE }}
          
    - name: Configure IntelliFactory CI git user
      run: |
        git config --global user.email "ci@intellifactory.com"
        git config --global user.name "IntelliFactory CI"

    - name: Check out build-script
      uses: actions/checkout@v2
      with:
        path: build-script

    - name: Check out WS Core
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/core
        ref: net8upgrade
        path: core
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS Core
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./core

    - name: Check out WS.UI
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/ui
        ref: net8upgrade
        path: ui
        token: ${{ secrets.PAT_PACKAGE }}
        
    - name: Update WS.UI
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./ui

    - name: Check out WS.MathJS
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/mathjs
        ref: net8upgrade
        path: mathjs
        token: ${{ secrets.PAT_PACKAGE }}
        
    - name: Update WS.MathJS
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./mathjs

    - name: Check out WS.AspNetCore.WebSocket
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/aspnetcore
        ref: net8upgrade
        path: aspnetcore
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}
        
    - name: Update WS.AspNetCore.WebSocket
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./aspnetcore

    - name: Check out WS.Templates
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/templates
        ref: net8upgrade
        path: templates
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}
        
    - name: Update WS.Templates
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./templates

    - name: Check out WS.JQuery
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/jquery
        ref: net8upgrade
        path: jquery
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.JQuery
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./jquery

    - name: Check out WS.Forms
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/forms
        ref: net8upgrade
        path: forms
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Forms
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./forms
      
    - name: Check out WS.MVU
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/mvu
        ref: net8upgrade
        path: mvu
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}
    
    - name: Update WS.MVU
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./mvu

    - name: Check out WS.Leaflet
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/leaflet
        ref: net8upgrade
        path: leaflet
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Leaflet
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./leaflet

    - name: Check out WS.D3
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/d3
        ref: net8upgrade
        path: d3
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.D3
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./d3

    - name: Check out WS.React
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/react
        ref: net8upgrade
        path: react
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.React
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./react

    - name: Check out WS.SignalR
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/signalr
        ref: net8upgrade
        path: signalr
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.SignalR
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./signalr

    - name: Check out WS.DateFNS
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/datefns
        ref: net8upgrade
        path: datefns
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.DateFNS
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./datefns

    - name: Check out WS.Moment
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/moment
        ref: net8upgrade
        path: moment
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Moment
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./moment

    - name: Check out WS.Plotly
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/plotly
        ref: net8upgrade
        path: plotly
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Plotly
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./plotly

    - name: Check out WS.ChartJS
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/chartjs
        ref: net8upgrade
        path: chartjs
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Chartjs
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./chartjs

    - name: Check out WS.Charting
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/charting
        ref: net8upgrade
        path: charting
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Charting
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./charting

    - name: Check out WS.Highcharts
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/highcharts
        ref: net8upgrade
        path: highcharts
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Highcharts
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./highcharts
      
    - name: Check out WS.HighlightJS
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/highlightjs
        ref: net8upgrade
        path: highlightjs
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.HighlightJS
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./highlightjs

    - name: Check out WS.MathJax
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/mathjax
        ref: net8upgrade
        path: mathjax
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.MathJax
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./mathjax

    - name: Check out WS.Elmish.React
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/elmish.react
        ref: net8upgrade
        path: elmish.react
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Elmish.React
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./elmish.react

    - name: Check out WS.SweetAlert
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/sweetalert
        ref: net8upgrade
        path: sweetalert
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.SweetAlert
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./sweetalert

    - name: Check out WS.Remarkable
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/remarkable
        ref: net8upgrade
        path: remarkable
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Remarkable
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./remarkable

    - name: Check out WS.JsPDF
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/jspdf
        ref: net8upgrade
        path: jspdf
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.JsPDF
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./jspdf

    - name: Check out WS.AnimeJS
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/animejs
        ref: net8upgrade
        path: animejs
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.AnimeJS
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./animejs

    - name: Check out WS.Popover
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/popover
        ref: net8upgrade
        path: popover
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Popover
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./popover

    - name: Check out WS.PerformanceAPI
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/performanceapi
        ref: net8upgrade
        path: performanceapi
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.PerformanceAPI
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./performanceapi

    - name: Check out WS.IndexedDB
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/w3c-indexeddb
        ref: net8upgrade
        path: w3c-indexeddb
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.IndexedDB
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./w3c-indexeddb

    - name: Check out WS.WebRTC
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/webrtc
        ref: net8upgrade
        path: webrtc
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.WebRTC
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./webrtc

    - name: Check out WS.FluentUI.React.Comp
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/fluentui-react-components
        ref: net8upgrade
        path: fluentui-react-components
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.FluentUI.React.Comp
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./fluentui-react-components

    - name: Check out WS.FluentUI.React.Icons
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/fluentui-react-icons
        ref: net8upgrade
        path: fluentui-react-icons
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.FluentUI.React.Icons
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./fluentui-react-icons

    - name: Check out WS.Browser
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/fable-browser
        ref: net8upgrade
        path: fable-browser
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Browser
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./fable-browser

    - name: Check out WS.FsLexYacc.Runtime
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/FsLexYacc.Runtime
        ref: net8upgrade
        path: lexyacc
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.FsLexYacc.Runtime
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./lexyacc

    - name: Check out WS.Feliz
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/feliz
        ref: net8upgrade
        path: feliz
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Feliz
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./feliz

    - name: Check out WS.Fable.Mocha
      uses: actions/checkout@v2
      with:
        repository: dotnet-websharper/WebSharper.Fable.Mocha
        ref: net8upgrade
        path: mocha
        fetch-depth: 0
        token: ${{ secrets.PAT_PACKAGE }}

    - name: Update WS.Fable.Mocha
      run: ../build-script/updateScripts/${{ github.event.inputs.updateFolder }}/update
      working-directory: ./mocha
    
